version: "3.9"

services:
  spark:
    image: docker.io/bitnami/spark:3.5.1
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

    ports:
      - "8080:8080"
    volumes:
      - ./src/:/opt/bitnami/sample_process/

  spark-worker:
    image: docker.io/bitnami/spark:3.5.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

  sbt:
    image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1
    environment:
      - BASE_IMAGE_TAG="8u212-b04-jdk-stretch"
      - SBT_VERSION="1.3.5"
      - SCALA_VERSION="2.13.1"
      - USER_ID=1001
      - GROUP_ID=1001
    command: tail -f /scala_app/dataformat/src/main/scala/dataformat.scala
    volumes:
      - ./src/scalaSpark/:/scala_app/
